### Criar um jogo
POST http://localhost:3333/jogos
Content-Type: application/json

{
    "title": "overwatch",
    "description": "O mais novo jogo da Rockstar Games",
    "price": 20,
    "platform": "PS4",
    "genre": "Luta"
}

###

### Listar todos os jogos
GET http://localhost:3333/jogos

###

### Buscar jogo por nome
GET http://localhost:3333/jogos?search=GTA

###

### Atualizar um jogo
PUT http://localhost:3333/jogos/c809aec3-39f9-4826-872a-7d5c6febeeed
Content-Type: application/json

{
    "title": "GTA 5",
    "description": "Descrição atualizada",
    "price": 70.00,
    "platform": "PS4",
    "genre": "Ação"
}

###

### Deletar um jogo
DELETE http://localhost:3333/jogos/0377cde3-50cb-439e-a1f6-0e6b2fddc59c